# standard jekyll stuff
timezone: America/Chicago
permalink: /posts/:year/:month/:title.html
markdown: rdiscount
exclude:
 - Rakefile
 - config.rb

# configuration required for some pages
domain: stevector.com
title: stevector.com
author: stevector
email: steve@stevepersch.com

# configuration third-party integration.

github:
  username: stevector

twitter:
  username: stevector

disqus:
  id: stevector

google_analytics:
  account: UA-42048647-1
